export * from "./access-risk";
export * from "./azureReportProvider";
export * from "./domain/entra";
export * from "./domain/resources";
export * from "./entra-consent";
export * from "./exportedCollections";
export * from "./identities";
export * from "./ownership";
export * from "./reportConfig/azureReportConfig";
