export type AzureActivityLog = {
  subscriptionId: string;
  subscriptionName: string;
  eventTimestamp: string;
  submissionTimestamp: string | null;
  caller: string | null;
  callerUserPrincipalName?: string | null;
  callerName?: string | null;
  callerEmail?: string | null;
  callerObjectId?: string | null;
  callerIdentityType?: string | null;
  callerAppId?: string | null;
  callerIpAddress?: string | null;
  callerTenantId?: string | null;
  operationName: string | null;
  operationNameValue: string | null;
  status: string | null;
  subStatus: string | null;
  category: string | null;
  resourceGroupName: string | null;
  resourceId: string | null;
  resourceProviderName: string | null;
  resourceType: string | null;
  authorizationAction: string | null;
  authorizationScope: string | null;
};
